version: '3.8'

services:
  web:
    build:
      context: .
    container_name: projeto-web-5001
    ports:
      - "8001:5001"
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped
